# CONFIGURATION
# https://jekyllrb.com/docs/configuration/options/

title: learnlatex.org
description: Learn LaTeX online
repository: learnlatex/learnlatex.github.io

plugins:
  - jekyll-sitemap

kramdown:
    syntax_highlighter_opts:
      disable: true

sass:
    style: compressed

limit_posts: 0


# HTML COMPRESSION
# Compress HTML with http://jch.penibelst.de/
# The compression file is _layout/compress.html
# https://jch.penibelst.de/#configuration
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

